=== Molizo/ContractGenerator/wwwroot/Data/companies-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Companies",
  "type": "array",
  "items": {
    "title": "Company",
    "type": "object",
    "properties": {
      "Name": {
        "type": "string"
      },
      "Address": {
        "type": "string"
      },
      "City": {
        "type": "string"
      },
      "CIF": {
        "type": "string"
      },
      "IBAN": {
        "type": "string"
      },
      "BankName": {
        "type": "string"
      },
      "SWIFT": {
        "type": "string"
      },
      "RepresentativeName": {
        "type": "string"
      },
      "RepresentativeTitle": {
        "type": "string"
      },
      "OtherInfoHeader": {
        "type": "string"
      },
      "OtherInfoBeneficiary": {
        "type": "string"
      }
    },
    "required": [
      "Name",
      "Address",
      "City",
      "CIF",
      "IBAN",
      "BankName",
      "SWIFT",
      "RepresentativeName",
      "RepresentativeTitle",
      "OtherInfoHeader",
      "OtherInfoBeneficiary"
    ]
  }
}

=== Molizo/ContractGenerator/ProductionWebsite/Data/companies.json
[
  {
    "Name": "ASOCIATIA PENTRU UN VIITOR STRALUCIT IMPREUNA",
    "Address": "Șos. Colentina nr. 22, bl. 9C, sc. A, et. 8, ap. 33, Sector 2",
    "City": "București",
    "CIF": "43240724",
    "IBAN": "RO98PIRB4205749666001000",
    "BankName": "FIRST Bank",
    "SWIFT": "PIRBROBU",
    "RepresentativeName": "KIZIL OLCAY",
    "RepresentativeTitle": "Membru Fondator",
    "OtherInfoHeader": "Registrul Unităților de Cult din 18.11.2020",
    "OtherInfoBeneficiary": ", înregistrată în Registrul entităților/unităților de cult începând cu data de 18 noiembrie 2020"
  },
  {
    "Name": "ASOCIATIA URBAN FAN",
    "Address": "Bld. Ion Mihalache, Nr. 144, Bl. 10, Et. 9, Ap 38",
    "City": "București",
    "CIF": "44243907",
    "IBAN": "RO11BREL0002003040110100",
    "BankName": "Libra Internet Bank",
    "SWIFT": "BRELROBUXXX",
    "RepresentativeName": "Daniel-Ioan Calinescu",
    "RepresentativeTitle": "Presedinte",
    "OtherInfoHeader": "",
    "OtherInfoBeneficiary": ""
  }
]
